# This file was generated by GoReleaser. DO NOT EDIT.
cask "aki" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d67272c022b9fc30a56970762b63a22c39f3c544ed67f03e3fa5f44213f5db51"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6be1c5ce643b8f9c384a131488070bb5f0263ba1a05763e611c5ff8dfa92c93c"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bbdcbb0106b1d5090f3e9e6a9aea33364fcdda8ab2df31b8a9b9a5738361d9d4"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f266b1f5da653ef9e592ab1d9451d6708a911299427592ca913a98301995c9b"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aki"
  desc "A Redis-compatible database in a single file"
  homepage "https://github.com/tamnd/aki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aki"

  # No zap stanza required

end
