# This file was generated by GoReleaser. DO NOT EDIT.
cask "aki" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "411cb6fe9c5e47da22e4e918da857a5fea7cd74ecab6724a20658cf0df2822e7"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a3100e511968b138b9a0b7ca7cb274c19e2aff73451b1b473a5a6e71b417097"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42b294696291050c1748f51b75f0119ce7928a1ef19db59a2bf67e895656c7e3"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2a207339c3b35f8910efc43b10586fe5ab7f9badc7bb422e102eece4b5b0d77"
      url "https://github.com/tamnd/aki/releases/download/v#{version}/aki_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aki"
  desc "A Redis-compatible database in a single file"
  homepage "https://github.com/tamnd/aki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aki"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aki"]
  end

  # No zap stanza required

end
