# This file was generated by GoReleaser. DO NOT EDIT.
cask "ami" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "179c10c0cdc2ca445d908c4ae709d11f3b2bb38ccda54930d2b04387a6f2672e"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28e8d513eb3cb3d5c48535455fe78fb64f816a1471eefc9c580bf0dd0f9d5bf9"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fdeb70811ac79501e715070c92795ba2abdadb468f795f0aec6889c8826c65cf"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3a472d109480adceecfd79e34958dc632e3d2959dd1a2e68ce2670ae2a1acbb"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ami"
  desc "Re-fetch every URL in a seed and pack the results into WARC files and a Parquet index"
  homepage "https://github.com/tamnd/ami"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ami"

  # No zap stanza required

end
