# This file was generated by GoReleaser. DO NOT EDIT.
cask "ami" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f87124f880315b9271011811669a1f93e6a98b66f9bb5873fb0364fe90ead334"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddec0532a9dfdbf0155f961fabc3a5e6843f2e829cf516e04b9dda563f29e6f1"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dcd3b8b6c79bbf7ff3ea0573d9b9c24bd7916c9fafdc30ba7973116d176db020"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7e6a601ff5fd33be8cc89d00f323ce41c8a815d2420067c13b2f949914c5add"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ami"
  desc "Re-fetch every URL in a seed and pack the results into WARC files and a Parquet index"
  homepage "https://github.com/tamnd/ami"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ami"

  # No zap stanza required

end
