# This file was generated by GoReleaser. DO NOT EDIT.
cask "ami" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1748c7f60ebeace63793d30957951a23feb4be11c46dd643655e979c1627076e"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "32d7d6917254739a85576e07e2247006c26ea7834c233a0747b8fe45ae90dd24"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "acb6dcaa6e1628ad1aeb9a98f1e16a7e232b529f81ad9a9be12505e6dbda504e"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb77a95c0db9c71c736fa3f9556e01b94622433b8ff5a8ebbe08e32ece3b37cb"
      url "https://github.com/tamnd/ami/releases/download/v#{version}/ami_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ami"
  desc "Re-fetch every URL in a seed and pack the results into WARC files and a Parquet index"
  homepage "https://github.com/tamnd/ami"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ami"

  # No zap stanza required

end
