# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccrawl" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "137640956608556b83e83dc70e86c6db4f307034bf86a4effc13357a4f8a90ff"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc113d5c81a12c90d6ad6f73d4d438f079d6136463920fcd76a94643e366dac2"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb9636a64d508d71c67fc0dbae6c329b984e7cc9f03e57669538f46d74dbc939"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ec8e0479623ea35020b810c3557fd28fabd3c5b12462e577f42982b46e08774"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccrawl"
  desc "A fast, friendly command line for Common Crawl"
  homepage "https://github.com/tamnd/ccrawl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccrawl"

  # No zap stanza required

end
