# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccrawl" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "c834f54a0a5a9a0bd8818ebace0cb8d3c9abf6a0cb0e3ffb2ef43e8ece445137"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "229a081c434ec9e16c0eb38641c51da1b20c8c2dcf238fb66fa1bd3cdc749996"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82309d91c2730c336802f3d5b99dc5cdc3e164eadf45bc2ef005ea2bb3eaad16"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f97af043e3e54db7031e8cc028095759a043f57dc867997268d338c5dd26c406"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccrawl"
  desc "A fast, friendly command line for Common Crawl"
  homepage "https://github.com/tamnd/ccrawl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccrawl"

  # No zap stanza required

end
