# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccrawl" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "fb071d5c545bca4a4b8e189e00e52e939166fdf5c2aaf5b5687c0f776452f929"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8691c5f35618d2c2ab41c6da4c6d63fbc6d507e9dec62118fd1e51e8f5c852d"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2640f0e7f3b227e7e737c65c40db87c53dfcea47e293695c8a3304769fd6d744"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "28bf09d9638e1856509c28eb86cdbd92bf0869d9fb11503cdc293c12adbed99c"
      url "https://github.com/tamnd/ccrawl-cli/releases/download/v#{version}/ccrawl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ccrawl"
  desc "A fast, friendly command line for Common Crawl"
  homepage "https://github.com/tamnd/ccrawl-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccrawl"

  # No zap stanza required

end
