# This file was generated by GoReleaser. DO NOT EDIT.
cask "kage" do
  version "0.3.9"

  on_macos do
    on_intel do
      sha256 "7409bd53aaf9bd9d6105978ccac208e2ec617f927c24091e483f2b9944b03dfe"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "17ea65d25629af2b398b0cf5cba26c5b1e3a6570355e990483bccb1908883641"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "012d7cdd27bf410300bd8c5cc811a635dd8721b2a96a71a4d2dc775f699e5218"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b70beadf2e49677776001d9ab687af60111897fe5f3126c689915838a560282a"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kage"
  desc "Clone any website for offline viewing, with the JavaScript stripped out"
  homepage "https://github.com/tamnd/kage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kage"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kage"]
    end
  end

  # No zap stanza required

end
