# This file was generated by GoReleaser. DO NOT EDIT.
cask "kage" do
  version "0.3.8"

  on_macos do
    on_intel do
      sha256 "95d98d14b61958cb1514eea70e259ca302f32501c678327e1e8c0aeec5e074cb"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b12687d8664109154bc14d85b2b00c89185c7b4e81fda700c0a50efcb211d562"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "056e284b9c470ef07ed8ceab4f16ac6e9469f161b4a5d077ff1b41a8cd07b698"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0ea88f456d407cd57f0ff908a83f018cdf54faccf993ab8149b66f3f13fa8f3"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kage"
  desc "Clone any website for offline viewing, with the JavaScript stripped out"
  homepage "https://github.com/tamnd/kage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kage"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kage"]
    end
  end

  # No zap stanza required
end
