# This file was generated by GoReleaser. DO NOT EDIT.
cask "kage" do
  version "0.3.7"

  on_macos do
    on_intel do
      sha256 "8184ac6f8c440698946a848fc1eec2fc3c952a3859d6410cdca03ba1af93b15b"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a33724127dcfcef7af4ed11d913cacc12cad400a04f4e1fe897dcf440d7c84c9"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe14c7c447a9bafa9399108634ef84f6a3e2cf89572731db486809c92d4b983e"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4b001554509a5ac06888fb0ca061ce1d4964fd41eebfdc31cace91735e7c11a"
      url "https://github.com/tamnd/kage/releases/download/v#{version}/kage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kage"
  desc "Clone any website for offline viewing, with the JavaScript stripped out"
  homepage "https://github.com/tamnd/kage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kage"

  # No zap stanza required

end
