# This file was generated by GoReleaser. DO NOT EDIT.
cask "kv" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2839b60617acf19490c5681490c32e5cd2c706711e9f57cf262c91747687cf69"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46aebb6926272f7a52336f4e217f72a62a9bf325c3dae05b63bc3fbc5d7a075d"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a87648d4c8aec9ac32b72c5795e0ab45fb5edc4faf011eff83121d3a8797e93d"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2441f83e88f9ba36e8534924fef475a9ecd4442200270d30183f9a8f14395555"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kv"
  desc "Embeddable ordered key/value database for Go, in a single file with zero dependencies"
  homepage "https://github.com/tamnd/kv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kv"

  # No zap stanza required

end
