# This file was generated by GoReleaser. DO NOT EDIT.
cask "kv" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "afd4580aaaa3ab0290d37e37446c1751c39ca43116574b3a1178889193264c0b"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53d64b7b5991c93caad76da8f042aa5bd469689e5400f25ee9d47e5e88f332e1"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2907a20295f1f70bc395bff0be10e15f72f391b146830b9666da25533303bc7d"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f19671242c2ef1c586ebd954b9ad7f79e0695e24ff281ebb714273d3eaf614d"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kv"
  desc "Embeddable ordered key/value database for Go, in a single file with zero dependencies"
  homepage "https://github.com/tamnd/kv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kv"

  # No zap stanza required

end
