# This file was generated by GoReleaser. DO NOT EDIT.
cask "kv" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9a624a8ff65cb168697c7b12d845fbd64e7f93bcdafdae39b9ea473c8ff62e4f"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6cc36913254617f772a98a395c694a0568fbe067f60dfefdcb15d6a89459592"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9f8fbb4c879b5b296a952c3200e2923c976e7ac99c0d7753586332ed577476c"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e52240ac775701730ca9bea582c606c3911343fc34fca4d66e6e7b2ef5fdbba2"
      url "https://github.com/tamnd/kv/releases/download/v#{version}/kv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kv"
  desc "Embeddable ordered key/value database for Go, in a single file with zero dependencies"
  homepage "https://github.com/tamnd/kv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kv"

  # No zap stanza required

end
