# This file was generated by GoReleaser. DO NOT EDIT.
cask "meguri" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2024b7536e503f10cdc6461affd59a0e4c28879d232f2015b370b1b29738c193"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78d5d7aa31bd6d53a458b00426d7e4bfdb8bdc7d465ab5043e4ee5e8363fbd8a"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa1d40cb8d4b9b36eab3ea15d4bac88ee383cbc7a40d3fe81e5e8a3145506e8e"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "97c8b4a03f44a606fe7cce3ed80f3aea29eb563a13727c9906005339e5f08db1"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_linux_arm64.tar.gz"
    end
  end

  name "meguri"
  desc "A distributed web-crawler frontier and rescheduler on compact single-file partitions"
  homepage "https://github.com/tamnd/meguri"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meguri"

  # No zap stanza required

end
