# This file was generated by GoReleaser. DO NOT EDIT.
cask "meguri" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "346d53c5b596246e13cc7b533b00b82dcee572626d0a41f2a897db4bc36d9d3f"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7d1d958989b9f8bb8faca8c5f766b5475a17a250f8800ea29aed0eca7ad271d"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d32ce02aff6583d002d401040cad4b81ad311f0469bfcef476c3faa43aa5ee36"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d12d21ea99cca73860b75d25ca6ea00952a0cf6bacd95f4d9b0d0cea25d634e"
      url "https://github.com/tamnd/meguri/releases/download/v#{version}/meguri_#{version}_linux_arm64.tar.gz"
    end
  end

  name "meguri"
  desc "A distributed web-crawler frontier and rescheduler on compact single-file partitions"
  homepage "https://github.com/tamnd/meguri"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meguri"

  # No zap stanza required

end
