# This file was generated by GoReleaser. DO NOT EDIT.
cask "shirabe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f57358a1ea40076f398feabdd810214660745807cba36b5763db5068de1d8af7"
      url "https://github.com/tamnd/shirabe/releases/download/v#{version}/shirabe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3881ad8a5c605c3f2b471d4955d1c18071037c038245663334b3d23c429270f1"
      url "https://github.com/tamnd/shirabe/releases/download/v#{version}/shirabe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "98f3c06a70d6b7c0455228459425739712e999ca4177a7d2709e931cbbf44e80"
      url "https://github.com/tamnd/shirabe/releases/download/v#{version}/shirabe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdb6cc8cbf4c86d5d4ed1bcd028acf3bd82a84e59e74595054815925de4f8651"
      url "https://github.com/tamnd/shirabe/releases/download/v#{version}/shirabe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shirabe"
  desc "One search box over every source you already have, rendered as rich cards"
  homepage "https://github.com/tamnd/shirabe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shirabe"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shirabe"]
    end
  end

  # No zap stanza required
end
