# This file was generated by GoReleaser. DO NOT EDIT.
cask "tatami" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "dd74864b14eb51a00c223555d941535b798ff3f59058be1110c3960d0a04d66f"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9efd7376d90cd4d38799a2d649252ecaf571c20cb454f85c14d9c45ec2068de3"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d10f8a69d89966295f229091fb7fd1f0b8b5feb93a2e27aafa37ee3c0e8a97e"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9806bc4c36b04b164eb5af9038905369d8c704ba0fc8c74ecc466b05640ea215"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tatami"
  desc "A compact columnar single-file format for web-scale crawl and search"
  homepage "https://github.com/tamnd/tatami"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tatami"

  # No zap stanza required

end
