# This file was generated by GoReleaser. DO NOT EDIT.
cask "tatami" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2fa53e7e76142d1a2c3a8e01dbce2264ccc868082353bd50caae8f761ec4fab4"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b7999f2f46db62b51a863ae6c1873d47ab26b35590bfed2765ee8c43dc2844e"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90cb3826e2f5db9e031851184090dbfd56b5a4e59d0c6892bbb7bd4e32a25d20"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc47342cde1fc52e5b6a63f97657ea029e8fa942271a27c2686bf5a5697ee9cd"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tatami"
  desc "A compact columnar single-file format for web-scale crawl and search"
  homepage "https://github.com/tamnd/tatami"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tatami"

  # No zap stanza required

end
