# This file was generated by GoReleaser. DO NOT EDIT.
cask "tatami" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "19097dfd07b124658eb60ed5c4151080faf64671dcae92035d0f14f819fbb4c9"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b98dcc97d86aa4381abe934874a2e3be2766b8ff04f8c1763ef839af6e5f7993"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0227587f8a5056defa7c809426b228e7b74f6f5a0b473528252a841e2a00ce5c"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcdbb19bac3ae73d2fef7d3762caf02037138581afec05903c8fea268ee326af"
      url "https://github.com/tamnd/tatami/releases/download/v#{version}/tatami_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tatami"
  desc "A compact columnar single-file format for web-scale crawl and search"
  homepage "https://github.com/tamnd/tatami"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tatami"

  # No zap stanza required

end
