# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomo" do
  version "0.2.11"

  on_macos do
    on_intel do
      sha256 "1e90797c77ef03ecca86a73928554f31cf4ff659424c136b56cbe21df718ccfc"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bb08240540ca4d4e0f9ed6c13916b8336df089e8554933b67da645c4a605cd3"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a14946bd80a09d94d7133bda21ee78582ea140b123d0d41dc7239e283fe3028e"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f381a03688dd70899eda077528e1848fecd907ba4de9e567a7bc6d17d4331f7"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tomo"
  desc "Your personal AI agent, one Go binary"
  homepage "https://github.com/tamnd/tomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomo"

  # No zap stanza required

end
