# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomo" do
  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "ca2734ac5eed1f42fc45e6c70aecc97d81ae62c66d5c51270a2482ebd2b7bc72"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63102ee7bdf8a24eb10a6e2755c4114e555b4f82453bd204685eb31216710814"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f023613861b88fd030570d53f206a5747ce7b3a985996d68d8587164cec3f890"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b47943a3583b40f267c96771d8bb7afeb50d92c9735650dede9308eebb5d6f5"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tomo"
  desc "Your personal AI agent, one Go binary"
  homepage "https://github.com/tamnd/tomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomo"

  # No zap stanza required

end
