# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomo" do
  version "0.2.12"

  on_macos do
    on_intel do
      sha256 "04deb75361b0b548cde6a35da76f3b2be3e519a70b0a9fbdd37441273211e235"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f83ef66c3af542fa03a17b48a861278dc92edb221a17a48a938f9e2997cb15d3"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d8dceea47c114d359325d5164e8f8faa8ee639b5da9615925dc4d46503b8e57"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6725353037268424a5103be4af2a5054eb79ef5d652f1a5fd2ff076183a33464"
      url "https://github.com/tamnd/tomo/releases/download/v#{version}/tomo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tomo"
  desc "Your personal AI agent, one Go binary"
  homepage "https://github.com/tamnd/tomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomo"

  # No zap stanza required

end
