# This file was generated by GoReleaser. DO NOT EDIT.
cask "tori" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "78c73fdc222e822fcb5d511d5e97c265adb670d44e4703d15f96f2e7d7c1beed"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "04cc6545adb846001d9d6cc62b0d88c5614914575080cc3f6037cfcc5e51aa9e"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe3024c6cff8b51d2b01231b6caa7c30d0991026eb84f9780ec0f96df2d8089a"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88b811918d1b15c450b27f394de36bfb73ae21dcd8e57a9d11be133116c7a24c"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tori"
  desc "Build offline, browsable archives of X (Twitter) content"
  homepage "https://github.com/tamnd/tori"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tori"

  # No zap stanza required

end
