# This file was generated by GoReleaser. DO NOT EDIT.
cask "tori" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "19eda3e205029f43f2e8d81a514b668775f957217a5e13c583a06dca36b08e2d"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66a1706acb22711cc3e19793dd6a059fe7ffcb11fc7377bd343fcbefa7b8ad98"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a87a71bd7766096aff010f4d8ba9cedfdd5498acbdf46635ea7e193652e29a0c"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b20a4d5c4f10e84ac684812e1e7c5f9f7edcd97f6d003ea8ae57ff216a779599"
      url "https://github.com/tamnd/tori/releases/download/v#{version}/tori_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tori"
  desc "Build offline, browsable archives of X (Twitter) content"
  homepage "https://github.com/tamnd/tori"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tori"

  # No zap stanza required

end
