# This file was generated by GoReleaser. DO NOT EDIT.
cask "yomi" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "54324faa86c99ed918be1e00c784cace8e88f86453af4bc84a7c0bf90397ea61"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "25a9a5916f9f8f385972dd0dcce24121c28a143e00b3ce8c96b1cb4445cee8fc"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a00be771f77a2b416f26ba4cf4c2fdeeece9ab66ab1322c084fdedebbbd5430"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "191dbd8cbd10500ef264cc2c100d099064bb9c6f21911f3f5747adfd286ca602"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yomi"
  desc "Read any web page, or a whole website, into clean Markdown"
  homepage "https://github.com/tamnd/yomi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yomi"

  # No zap stanza required

end
