# This file was generated by GoReleaser. DO NOT EDIT.
cask "yomi" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "bf73cfb92deade7cc96dcd2be6fcb436fc4289cbd3be76df8247d3563c933103"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3f231ffb505a7c2d4c660fd00fd95c7c8854a208d5fb7af9b249601146a8533"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "810faa52d7a6001fe27ba504cd0594845f9a259b9267327f37b822b896966a98"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "178339b39a1936db495c1cfe26da29004ca63271bb30fb784827f9a1cad8dcd2"
      url "https://github.com/tamnd/yomi/releases/download/v#{version}/yomi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yomi"
  desc "Read any web page, or a whole website, into clean Markdown"
  homepage "https://github.com/tamnd/yomi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yomi"

  # No zap stanza required

end
